remote_theme: Sustainamo/cayman
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Sustainamo
description: Guidance for creating an organisation or event sustainability strategy
